### PR TITLE
fix: --compact with --json depUrl

### LINKED ISSUE #340: The flag `--compact` with `--json` doesn't return the short SHA
I recently set up the Biome infra to create preview releases of the package `@biomejs/biome`.

We do this in a custom way. We use a command like this:

```shell
pnpx pkg-pr-new publish --compact './packages/@biomejs/biome' --json output.json --comment=off
```

And then a very simple script:

```js
const fs = require('fs');
const output = JSON.parse(fs.readFileSync('output.json', 'utf8'));
const biomePackage = output.packages
  .find((p) => p.name === "@biomejs/biome");

return "New preview release available for `@biomejs/biome`. Install using the following command:\n ```bash\n npm i " + biomePackage.url + "\n```";
```

However seems to be the LONG URL. In fact, the message sent to discord is like this:

```bash
 npm i https://pkg.pr.new/biomejs/biome/@biomejs/biome@bca10f5198a6afaeffdcf7116f65444f9e11f674
```

### PR DESCRIPTION
**Pull request by AmirSa12**
fixes #340

### CODE REVIEW

File: packages/cli/index.ts [hunk 1]
```diff
@@ -222,7 +222,7 @@ const main = defineCommand({
             }
 
             const depUrl = new URL(
-              `/${owner}/${repo}/${pJson.name}@${sha}`,
+              `/${owner}/${repo}/${pJson.name}@${isCompact ? abbreviateCommitHash(sha) : sha}`,
```
Comment (Aslemammad) [inline packages/cli/index.ts:225]: i think the condition part can be DRYed with the the change in the bottom

**Review by Aslemammad — CHANGES_REQUESTED** [review]

File: packages/cli/index.ts (hunk 1 above)
Comment (AmirSa12) [reply packages/cli/index.ts]: Yup! good catch

**Review by Aslemammad — APPROVED** [review]
